development:
  adapter: postgresql
  encoding: utf8
  database: differenzia_development
  username: postgres
  password: asdf

test: &test
  adapter: postgresql
  encoding: utf8
  database: differenzia_test
  username: postgres
  password: asdf



cucumber:
  <<: *test
