require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ImportTablesController do

  def mock_import_table(stubs={})
    @mock_import_table ||= mock_model(ImportTable, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all import_tables as @import_tables" do
      ImportTable.stub(:all) { [mock_import_table] }
      get :index
      assigns(:import_tables).should eq([mock_import_table])
    end
  end

  describe "GET show" do
    it "assigns the requested import_table as @import_table" do
      ImportTable.stub(:find).with("37") { mock_import_table }
      get :show, :id => "37"
      assigns(:import_table).should be(mock_import_table)
    end
  end

  describe "GET new" do
    it "assigns a new import_table as @import_table" do
      ImportTable.stub(:new) { mock_import_table }
      get :new
      assigns(:import_table).should be(mock_import_table)
    end
  end

  describe "GET edit" do
    it "assigns the requested import_table as @import_table" do
      ImportTable.stub(:find).with("37") { mock_import_table }
      get :edit, :id => "37"
      assigns(:import_table).should be(mock_import_table)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created import_table as @import_table" do
        ImportTable.stub(:new).with({'these' => 'params'}) { mock_import_table(:save => true) }
        post :create, :import_table => {'these' => 'params'}
        assigns(:import_table).should be(mock_import_table)
      end

      it "redirects to the created import_table" do
        ImportTable.stub(:new) { mock_import_table(:save => true) }
        post :create, :import_table => {}
        response.should redirect_to(import_table_url(mock_import_table))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved import_table as @import_table" do
        ImportTable.stub(:new).with({'these' => 'params'}) { mock_import_table(:save => false) }
        post :create, :import_table => {'these' => 'params'}
        assigns(:import_table).should be(mock_import_table)
      end

      it "re-renders the 'new' template" do
        ImportTable.stub(:new) { mock_import_table(:save => false) }
        post :create, :import_table => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested import_table" do
        ImportTable.stub(:find).with("37") { mock_import_table }
        mock_import_table.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :import_table => {'these' => 'params'}
      end

      it "assigns the requested import_table as @import_table" do
        ImportTable.stub(:find) { mock_import_table(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:import_table).should be(mock_import_table)
      end

      it "redirects to the import_table" do
        ImportTable.stub(:find) { mock_import_table(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(import_table_url(mock_import_table))
      end
    end

    describe "with invalid params" do
      it "assigns the import_table as @import_table" do
        ImportTable.stub(:find) { mock_import_table(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:import_table).should be(mock_import_table)
      end

      it "re-renders the 'edit' template" do
        ImportTable.stub(:find) { mock_import_table(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested import_table" do
      ImportTable.stub(:find).with("37") { mock_import_table }
      mock_import_table.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the import_tables list" do
      ImportTable.stub(:find) { mock_import_table }
      delete :destroy, :id => "1"
      response.should redirect_to(import_tables_url)
    end
  end

end
